import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import YourCartButton from "@/components/cartButton";
import { CartProvider } from "@/contexts/CartContext";
import TransparentResponsiveHeader from "@/components/HeaderDrawer";
import { Box } from "@mui/material";
import { UserProvider } from "@/contexts/UserContext";
import { MapProvider } from "@/contexts/MapContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: 'white' }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <CartProvider>
            <TransparentResponsiveHeader />
            <MapProvider>
              <Box paddingTop={8}>
                {children}
              </Box>
            </MapProvider>


            <YourCartButton />

          </CartProvider>
        </UserProvider>


      </body>
    </html>
  );
}
